name: Pull Request

on:
  pull_request:
    branches:
      - main
    paths-ignore:
    - 'README.md'

env:
  CHART_NAME: "rabbitmq-observability"
  KIND_VERSION: "0.10.0"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{github.event.pull_request.head.sha}}

    - name: Install Kind
      run: |
        curl -L -o kind https://github.com/kubernetes-sigs/kind/releases/download/v${KIND_VERSION}/kind-linux-amd64
        sudo install ./kind /usr/local/bin && rm kind
        kind version
        kind version | grep -q ${KIND_VERSION}

    - name: Create Kind Cluster
      run: |
        kind create cluster
        kubectl cluster-info

    # Set Up Helm
    - name: Set up Helm
      uses: azure/setup-helm@v4
      with:
        version: v3.7.0

    # Lint
    - name: Helm Lint
      run: |
        helm lint ${CHART_NAME}

    - name: Helm Package
      run: |
        helm package ${CHART_NAME}
